AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: scroll-tracker – captures scroll-depth events and writes to DynamoDB
Globals:
  Function:
    Timeout: 10
Resources:
  ScrollEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: scroll-events-${AWS::StackName}
      AttributeDefinitions:
      - AttributeName: sessionId
        AttributeType: S
      - AttributeName: ts
        AttributeType: N
      KeySchema:
      - AttributeName: sessionId
        KeyType: HASH
      - AttributeName: ts
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
  ScrollTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ScrollTrackerFunction-${AWS::StackName}
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: s3://survivalofthefeature/28bf01a91c6cf9e45b294dd31541f5f0
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ScrollEventsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ScrollEventsTable
      Events:
        TrackApi:
          Type: Api
          Properties:
            Path: /track
            Method: post
      Architectures:
      - x86_64
  ReadEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ReadEventsFunction-${AWS::StackName}
      Runtime: nodejs18.x
      Handler: read.handler
      CodeUri: s3://survivalofthefeature/28bf01a91c6cf9e45b294dd31541f5f0
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ScrollEventsTable
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: ScrollEventsTable
      Events:
        GetEventsApi:
          Type: Api
          Properties:
            Path: /events
            Method: get
Outputs:
  ApiUrl:
    Description: Invoke URL for POST /track
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/track
    Export:
      Name:
        Fn::Sub: ScrollTrackerApiUrl-${AWS::StackName}
  EventsApiUrl:
    Description: Invoke URL for GET /events
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/events
    Export:
      Name:
        Fn::Sub: ScrollTrackerEventsApiUrl-${AWS::StackName}
